
SOURCE_EPA = 'EPA'
SOURCE_CITIZEN_SELF = 'SELF-CTZN'
SOURCE_CHOICES = (
    (SOURCE_EPA, 'EPA SDWIS'),
    (SOURCE_CITIZEN_SELF, 'Self Reported - Citizen'),
)


REPORT_TYPE_VIOLATION = 'VIOLATION'
REPORT_TYPE_OBSERVATION = 'OBSERVATION'
REPORT_TYPE_CHOICES = (
    (REPORT_TYPE_VIOLATION, 'EPA Violation'),
    (REPORT_TYPE_OBSERVATION, 'Observation'),
)

SEVERITY_UNSPECIFIED = 'UNSPECIFIED'
SEVERITY_NOTED = 'NOTED'
SEVERITY_MINOR = 'MINOR'
SEVERITY_MAJOR = 'MAJOR'
SEVERITY_CATASTROPHIC = 'CATASTROPHIC'
SEVERITY_CHOICES = (
    (SEVERITY_UNSPECIFIED, 'Unspecified'),
    (SEVERITY_NOTED, 'Noted'),
    (SEVERITY_MINOR, 'Minor'),
    (SEVERITY_MAJOR, 'Major'),
    (SEVERITY_CATASTROPHIC, 'Catastrophic'),
)


REPORT_VERIFICATION_VERIFIED = 'VERIFIED'
REPORT_VERIFICATION_UNVERIFIED = 'UNVERIFIED'
REPORT_VERIFICIATION_CHOICES = (
    (REPORT_VERIFICATION_VERIFIED, 'Verified'),
    (REPORT_VERIFICATION_VERIFIED, 'Unverified'),
)

REPORT_STATUS_OPEN = 'OPEN'
REPORT_STATUS_RESOLVED = 'RESOLVED'
REPORT_STATUS_CLOSED = 'CLOSED'
REPORT_STATUS_CHOICES = (
    (REPORT_STATUS_OPEN, 'Open'),
    (REPORT_STATUS_CLOSED, 'Closed'),
    (REPORT_STATUS_RESOLVED, 'Resolved'),
)

